build:
	echo "// Built proxy file" > dist.js
	echo "// Copies config.js, session.js, proxy.js together" >> dist.js
	echo "" >> dist.js
	echo "" >> dist.js

	echo "// config.js" >> dist.js
	echo "// =============================================================================" >> dist.js
	cat ./config.js >> dist.js
	echo "" >> dist.js
	echo "" >> dist.js

	echo "// session.js" >> dist.js
	echo "// =============================================================================" >> dist.js
	cat ./session.js >> dist.js
	echo "" >> dist.js
	echo "" >> dist.js

	echo "// proxy.js" >> dist.js
	echo "// =============================================================================" >> dist.js
	cat ./proxy.js >> dist.js
